### ISSUE TITLE
收录 一个稳定的占位图服务，支持CDN

### ISSUE THREAD

**Issue by hzlzh** [jserme/123.jser.us#12]
网站名 : temp.im
140字内描述 ： 稳定快速的占位图服务，使用Dropbox托管，七牛CDN加速
网址 ： http://temp.im/
标签 ： 占位符, placeholder

补充说明：这个服务已经2年多了，很稳定。

**Comment by jserme** [comment]
抱歉，这个服务我测试了一下并不是很稳定
![2014-06-29 10 23 12](https://cloud.githubusercontent.com/assets/451996/3423493/1ce542ce-ff99-11e3-8114-17383c6476a3.png)

**Comment by hzlzh** [comment]
@jserme 把红色部分的 URL 摘取出来访问下看是否出错？
比如你截图中的：
http://placeholder.qiniudn.com/26x26/FFCC00

![screen shot 2014-06-29 at 10 32 23 pm](https://cloud.githubusercontent.com/assets/1049575/3423513/5e22c85a-ff9a-11e3-92c5-22156706fefd.png)

另外：

这是七牛的CDN服务理论上不会有这样的问题，并且我测试过全国加速节点的。
测试结果见：
http://www.webkaka.com/webCheck.aspx?url=http%3A%2F%2Fplaceholder.qiniudn.com%2F26x26%2FFFCC00&sitesearch=0

![qq20140629-1](https://cloud.githubusercontent.com/assets/1049575/3423517/d4d808ca-ff9a-11e3-8b0f-bcdafa51120c.png)

所以再试一下吧，另外问一下你的网络运营商是什么？电信 联通？

**Comment by hzlzh** [comment]
如果是**联通**或者**网通**，七牛的CDN分发表现很慢，这个不是我能控制的，这个占位符一直在用没有遇到此类反馈。

下图：（左侧红框是网络类型，右侧红框是下载耗时）
![qq20140629-2](https://cloud.githubusercontent.com/assets/1049575/3423523/6837b3d6-ff9b-11e3-9d99-d314e01004ea.png)

**Comment by jserme** [comment]
@hzlzh 已经添加
