### ISSUE TITLE
Velocity.js

### ISSUE THREAD

**Issue by yuanxj1024** [jserme/123.jser.us#16]
网站名 : velocity.js
140字内描述 ： Velocity是完全免费的,更为轻量级，它大大地改善了UI动画性能和工作流程。
网址 ： http://velocityjs.org/
标签 ： 动画库

**Comment by jserme** [comment]
@yuanxj1024 
http://velocityjs.org/ 貌似被墙了，我直接用 http://julian.com/research/velocity/
