### ISSUE TITLE
推荐新的UI库

### ISSUE THREAD

**Issue by Hanruis** [jserme/123.jser.us#9]
网站名：semantic
说明：前端UI库
网址：http://semantic-ui.com/
标签：UI库

**Comment by jserme** [comment]
谢谢推荐，这个已经收录了

看这个提交
https://github.com/jserme/123.jser.us/commit/78ed7664cba66399390349ca897160958843457b

看来需要做一个搜索功能

**Comment by Hanruis** [comment]
噢噢。加油哈，已经关注了哈。
